title: raphaëlle tseng
description: A place to write about what I'm learning and the projects I'm interested in!

email: "raphaelletseng@gmail.com"
baseurl: ""
url: "raphaelletseng.github.io"
github_username: raphaelletseng
linkedin_username: raphaëlletseng

markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets

future: true
timezone: "Asia/Kuala_Lumpur"

google_analytics: 186144273
